Main changes: created cherrypy server, improved security of monhelper, updated code to django 1.10
GambitResearch/suponoff pull request #1
Opened 2016-11-27 13:01 UTC by lciti

I found suponoff an excellent dashboard for supervisor.
I have implemented some extra features I needed and I propose their inclusion in the main branch.
In particular:
- I have created a standalone server for the suponoff app using the production-ready cherrypy server
- I have made some changes to monhelper so it can be used with enhanced security
- I have made the code compatible with versions of django from 1.7 to 1.10

2016-11-29 13:30 UTC, gjcarneiro requested changes
Thanks for the PR.  I don't have any major objection, just some minor code style changes requested.

2016-11-29 13:30 UTC, gjcarneiro commented on suponoff-monhelper.py
> +    import argparse
Import inside function not justified, needs to be moved to toplevel.

2016-11-29 13:30 UTC, gjcarneiro commented on suponoff-server.py
> +
Again more imports inside functions is not pythonic.

2016-11-29 13:30 UTC, gjcarneiro commented on suponoff/views.py
> +except: # django==1.7
`except ImportError`, please.  Too wide exception catch.

2016-11-29 13:30 UTC, gjcarneiro commented on suponoff-monhelper.py
> +                    LOG.info("Process %s: %s", pid, e.msg)
Perhaps here it should log "No such process" instead of "Process"?

2016-11-29 22:52 UTC, lciti commented on suponoff-monhelper.py
> +                    LOG.info("Process %s: %s", pid, e.msg)
I am happy either way. Please notice that e.msg already describes the error, "Process %s: %s" gives: "Process 17487: no process found with pid 17487".

2016-11-29 23:20 UTC, lciti commented on suponoff/views.py
> +except: # django==1.7
Sure.

2016-11-29 23:26 UTC, lciti commented on suponoff-monhelper.py
> +    import argparse
I usually try to stick to PEP 8. My only exception is (like in this case) when a file could be used as a module and as a main. In this case I leave the main-specific imports within main. In any case, I am happy to move these imports to the beginning of the file as you prefer.

2016-11-29 23:27 UTC, lciti commented on suponoff-server.py
> +
Ok here too

2016-12-01 00:02 UTC, gjcarneiro approved these changes
Looks good, thanks!

2016-12-01 00:02 UTC, merged

2016-12-01 10:55 UTC, lciti commented
Great, many thanks to you!